# application.yml. *Make Rate Limit Configurable*,**Spring Cloud Config**:- Use Spring Cloud Config to make rate limit settings configurable and dynamic.
rate-limiter:
  max-requests: 100
  window-size: 60
  # application.yml
spring:
    cloud:
        config:
            enabled: false